INSERT INTO `interest_dic` VALUES (1, 'Neural Network', 1);
INSERT INTO `interest_dic` VALUES (2, 'Genetic Algorithm', 1);
INSERT INTO `interest_dic` VALUES (3, 'Machine Learning', 1);
INSERT INTO `interest_dic` VALUES (4, 'Data Structure', 1);
INSERT INTO `interest_dic` VALUES (5, 'High Performance', 1);
INSERT INTO `interest_dic` VALUES (6, 'Three Dimensional', 1);
INSERT INTO `interest_dic` VALUES (7, 'Sensor Network', 1);
INSERT INTO `interest_dic` VALUES (8, 'Wireless Network', 1);
INSERT INTO `interest_dic` VALUES (9, 'Distributed System', 1);
INSERT INTO `interest_dic` VALUES (10, 'Data Mining', 1);
INSERT INTO `interest_dic` VALUES (11, 'Information Retrieval', 1);
INSERT INTO `interest_dic` VALUES (12, 'Pattern Recognition', 1);
INSERT INTO `interest_dic` VALUES (13, 'Computational Complexity', 1);
INSERT INTO `interest_dic` VALUES (14, 'Operating System', 1);
INSERT INTO `interest_dic` VALUES (15, 'Programming Language', 1);
INSERT INTO `interest_dic` VALUES (16, 'Computer Vision', 1);
INSERT INTO `interest_dic` VALUES (17, 'Data Management', 1);
INSERT INTO `interest_dic` VALUES (18, 'collaborative system', 1);
INSERT INTO `interest_dic` VALUES (19, 'cooperative work', 1);
INSERT INTO `interest_dic` VALUES (20, 'e-Science', 1);
INSERT INTO `interest_dic` VALUES (21, 'network', 1);
INSERT INTO `interest_dic` VALUES (22, 'e-learning', 1);
INSERT INTO `interest_dic` VALUES (23, 'fuzzy system', 1);
INSERT INTO `interest_dic` VALUES (24, 'parallel systems', 1);
INSERT INTO `interest_dic` VALUES (25, 'Natural Language System', 1);
INSERT INTO `interest_dic` VALUES (26, 'Real-Time Systems', 1);
INSERT INTO `interest_dic` VALUES (27, 'XML Data', 1);
INSERT INTO `interest_dic` VALUES (28, 'Web Mining', 1);
INSERT INTO `interest_dic` VALUES (29, 'Virtual Environments', 1);
INSERT INTO `interest_dic` VALUES (30, 'DNA sequence', 1);
INSERT INTO `interest_dic` VALUES (31, 'Error detection', 1);
INSERT INTO `interest_dic` VALUES (32, 'grid', 1);
INSERT INTO `interest_dic` VALUES (33, 'cloud computing', 1);
INSERT INTO `interest_dic` VALUES (34, 'information recommendation', 1);
INSERT INTO `interest_dic` VALUES (35, 'Business Information', 1);
INSERT INTO `interest_dic` VALUES (36, 'Fault Tolerant', 1);
INSERT INTO `interest_dic` VALUES (37, 'Quality of Service', 1);
INSERT INTO `interest_dic` VALUES (38, 'Ad Hoc Network', 1);
INSERT INTO `interest_dic` VALUES (39, 'Optimization Problem', 1);
INSERT INTO `interest_dic` VALUES (40, 'Spectrum', 1);
INSERT INTO `interest_dic` VALUES (41, 'User Interface', 1);
INSERT INTO `interest_dic` VALUES (42, 'Support Vector Machine', 1);
INSERT INTO `interest_dic` VALUES (43, 'Software Engineering', 1);
INSERT INTO `interest_dic` VALUES (44, 'Software Systems', 1);
INSERT INTO `interest_dic` VALUES (45, 'Wireless Sensor Network', 1);
INSERT INTO `interest_dic` VALUES (46, 'Polynomial Time', 1);
INSERT INTO `interest_dic` VALUES (47, 'Learning Algorithm', 1);
INSERT INTO `interest_dic` VALUES (48, 'Artificial Intelligent', 1);
INSERT INTO `interest_dic` VALUES (49, 'Information System', 1);
INSERT INTO `interest_dic` VALUES (50, 'Wireless Communication', 1);
INSERT INTO `interest_dic` VALUES (51, 'Knowledge Base', 1);
INSERT INTO `interest_dic` VALUES (52, 'Mobile Robot', 1);
INSERT INTO `interest_dic` VALUES (53, 'Signal Processing', 1);
INSERT INTO `interest_dic` VALUES (54, 'Image Processing', 1);
INSERT INTO `interest_dic` VALUES (55, 'Software Development', 1);
INSERT INTO `interest_dic` VALUES (56, 'Linear Program', 1);
INSERT INTO `interest_dic` VALUES (57, 'Performance Analysis', 1);
INSERT INTO `interest_dic` VALUES (58, 'Peer To Peer', 1);
INSERT INTO `interest_dic` VALUES (59, 'Computer Graphic', 1);
INSERT INTO `interest_dic` VALUES (60, 'Web Service', 1);
INSERT INTO `interest_dic` VALUES (61, 'Approximate Algorithm', 1);
INSERT INTO `interest_dic` VALUES (62, 'Speech Recognition', 1);
INSERT INTO `interest_dic` VALUES (63, 'Maximum Likelihood', 1);
INSERT INTO `interest_dic` VALUES (64, 'Logic Programs', 1);
INSERT INTO `interest_dic` VALUES (65, 'Objective Function', 1);
INSERT INTO `interest_dic` VALUES (66, 'Feature Extraction', 1);
INSERT INTO `interest_dic` VALUES (67, 'Low Power', 1);
INSERT INTO `interest_dic` VALUES (68, 'Parallel Computer', 1);
INSERT INTO `interest_dic` VALUES (69, 'Computer Simulation', 1);
INSERT INTO `interest_dic` VALUES (70, 'Decision Making', 1);
INSERT INTO `interest_dic` VALUES (71, 'Natural Language', 1);
INSERT INTO `interest_dic` VALUES (72, 'Fading Channel', 1);
INSERT INTO `interest_dic` VALUES (73, 'Database System', 1);
INSERT INTO `interest_dic` VALUES (74, 'Dynamic Program', 1);
INSERT INTO `interest_dic` VALUES (75, 'Power Consumption', 1);
INSERT INTO `interest_dic` VALUES (76, 'Routing Protocol', 1);
INSERT INTO `interest_dic` VALUES (77, 'Communication System', 1);
INSERT INTO `interest_dic` VALUES (78, 'Distributed Computing', 1);
INSERT INTO `interest_dic` VALUES (79, 'Image Segmentation', 1);
INSERT INTO `interest_dic` VALUES (80, 'Semantic Web', 1);
INSERT INTO `interest_dic` VALUES (81, 'Performance Measure', 1);
INSERT INTO `interest_dic` VALUES (82, 'Decision Tree', 1);
INSERT INTO `interest_dic` VALUES (83, 'Image Sequence', 1);
INSERT INTO `interest_dic` VALUES (84, 'Mobile Ad Hoc Network', 1);
INSERT INTO `interest_dic` VALUES (85, 'Parameter Estimation', 1);
INSERT INTO `interest_dic` VALUES (86, 'Automatic Generation', 1);
INSERT INTO `interest_dic` VALUES (87, 'Object Recognition', 1);
INSERT INTO `interest_dic` VALUES (88, 'Perforation', 1);
INSERT INTO `interest_dic` VALUES (89, 'Cluster Algorithm', 1);
INSERT INTO `interest_dic` VALUES (90, 'Genetics', 1);
INSERT INTO `interest_dic` VALUES (91, 'Dynamic System', 1);
INSERT INTO `interest_dic` VALUES (92, 'Software Architecture', 1);
INSERT INTO `interest_dic` VALUES (93, 'Data Collection', 1);
INSERT INTO `interest_dic` VALUES (94, 'Probability Distribution', 1);
INSERT INTO `interest_dic` VALUES (95, 'Computer Program', 1);
INSERT INTO `interest_dic` VALUES (96, 'Energy Consumption', 1);
INSERT INTO `interest_dic` VALUES (97, 'Nonlinear System', 1);
INSERT INTO `interest_dic` VALUES (98, 'Feature Selection', 1);
INSERT INTO `interest_dic` VALUES (99, 'Community Networks', 1);
INSERT INTO `interest_dic` VALUES (100, 'Linear System', 1);
INSERT INTO `interest_dic` VALUES (101, 'Middleware', 1);
INSERT INTO `interest_dic` VALUES (102, 'Face Recognition', 1);
INSERT INTO `interest_dic` VALUES (103, 'Information Theory', 1);
INSERT INTO `interest_dic` VALUES (104, 'Information Technology', 1);
INSERT INTO `interest_dic` VALUES (105, 'Computer Model', 1);
INSERT INTO `interest_dic` VALUES (106, 'Base Station', 1);
INSERT INTO `interest_dic` VALUES (107, 'Computer Network', 1);
INSERT INTO `interest_dic` VALUES (108, 'Mobile Computer', 1);
INSERT INTO `interest_dic` VALUES (109, 'Steady State', 1);
INSERT INTO `interest_dic` VALUES (110, 'Linear Time', 1);
INSERT INTO `interest_dic` VALUES (111, 'Network Topology', 1);
INSERT INTO `interest_dic` VALUES (112, 'petri net', 1);
INSERT INTO `interest_dic` VALUES (113, 'Evolutionary Algorithm', 1);
INSERT INTO `interest_dic` VALUES (114, 'Generic Model', 1);
INSERT INTO `interest_dic` VALUES (115, 'Artificial Neural Network', 1);
INSERT INTO `interest_dic` VALUES (116, 'Wavelet Transform', 1);
INSERT INTO `interest_dic` VALUES (117, 'Message Passing', 1);
INSERT INTO `interest_dic` VALUES (118, 'Distributed Algorithm', 1);
INSERT INTO `interest_dic` VALUES (119, 'Scheduling Algorithm', 1);
INSERT INTO `interest_dic` VALUES (120, 'Parallel Programs', 1);
INSERT INTO `interest_dic` VALUES (121, 'Multi Agent System', 1);
INSERT INTO `interest_dic` VALUES (122, 'Human Computer Interaction', 1);
INSERT INTO `interest_dic` VALUES (123, 'Expert System', 1);
INSERT INTO `interest_dic` VALUES (124, 'Complex System', 1);
INSERT INTO `interest_dic` VALUES (125, 'Search Engine', 1);
INSERT INTO `interest_dic` VALUES (126, 'Simulated Annealing', 1);
INSERT INTO `interest_dic` VALUES (127, 'Experimental Evaluation', 1);
INSERT INTO `interest_dic` VALUES (128, 'Theoretical Analysis', 1);
INSERT INTO `interest_dic` VALUES (129, 'Mathematical Model', 1);
INSERT INTO `interest_dic` VALUES (130, 'Congestion Control', 1);
INSERT INTO `interest_dic` VALUES (131, 'Principal Component Analysis', 1);
INSERT INTO `interest_dic` VALUES (132, 'Oscillations', 1);
INSERT INTO `interest_dic` VALUES (133, 'Simulation Study', 1);
INSERT INTO `interest_dic` VALUES (134, 'Virtual Environment', 1);
INSERT INTO `interest_dic` VALUES (135, 'Information Theoretic', 1);
INSERT INTO `interest_dic` VALUES (136, 'Fuzzy Logic', 1);
INSERT INTO `interest_dic` VALUES (137, 'Cost Effectiveness', 1);
INSERT INTO `interest_dic` VALUES (138, 'Frequency Domain', 1);
INSERT INTO `interest_dic` VALUES (139, 'Medical Image', 1);
INSERT INTO `interest_dic` VALUES (140, 'Relational Database', 1);
INSERT INTO `interest_dic` VALUES (141, 'Image Analysis', 1);
INSERT INTO `interest_dic` VALUES (142, 'Virtual Reality', 1);
INSERT INTO `interest_dic` VALUES (143, 'Resource Allocation', 1);
INSERT INTO `interest_dic` VALUES (144, 'Embedded System', 1);
INSERT INTO `interest_dic` VALUES (145, 'Reinforcement Learning', 1);
INSERT INTO `interest_dic` VALUES (146, 'Query Processing', 1);
INSERT INTO `interest_dic` VALUES (147, 'Access Control', 1);
INSERT INTO `interest_dic` VALUES (148, 'Probabilistic Model', 1);
INSERT INTO `interest_dic` VALUES (149, 'Knowledge Representation', 1);
INSERT INTO `interest_dic` VALUES (150, 'Search Algorithm', 1);
INSERT INTO `interest_dic` VALUES (151, 'Em Algorithm', 1);
INSERT INTO `interest_dic` VALUES (152, 'Parallel Algorithm', 1);
INSERT INTO `interest_dic` VALUES (153, 'Markov Chain', 1);
INSERT INTO `interest_dic` VALUES (154, 'Similarity Measure', 1);
INSERT INTO `interest_dic` VALUES (155, 'Data Analysis', 1);
INSERT INTO `interest_dic` VALUES (156, 'Experimental Study', 1);
INSERT INTO `interest_dic` VALUES (157, 'kalman filter', 1);
INSERT INTO `interest_dic` VALUES (158, 'Scheduling Problem', 1);
INSERT INTO `interest_dic` VALUES (159, 'Fast Algorithm', 1);
INSERT INTO `interest_dic` VALUES (160, 'Low Complexity', 1);
INSERT INTO `interest_dic` VALUES (161, 'Association Rule', 1);
INSERT INTO `interest_dic` VALUES (162, 'File System', 1);
INSERT INTO `interest_dic` VALUES (163, 'Finite Element Method', 1);
INSERT INTO `interest_dic` VALUES (164, 'Parallel Processing', 1);
INSERT INTO `interest_dic` VALUES (165, 'Mutual Information', 1);
INSERT INTO `interest_dic` VALUES (166, 'Statistical Analysis', 1);
INSERT INTO `interest_dic` VALUES (167, 'Packet Loss', 1);
INSERT INTO `interest_dic` VALUES (168, 'bayesian network', 1);
INSERT INTO `interest_dic` VALUES (169, 'E Commerce', 1);
INSERT INTO `interest_dic` VALUES (170, 'Object Oriented Programming', 1);
INSERT INTO `interest_dic` VALUES (171, 'Open Source', 1);
INSERT INTO `interest_dic` VALUES (172, 'Data Stream', 1);
INSERT INTO `interest_dic` VALUES (173, 'Image Features', 1);
INSERT INTO `interest_dic` VALUES (174, 'Simulation Model', 1);
INSERT INTO `interest_dic` VALUES (175, 'Maximum Likelihood Estimate', 1);
INSERT INTO `interest_dic` VALUES (176, 'Social Network', 1);
INSERT INTO `interest_dic` VALUES (177, 'Edge Detection', 1);
INSERT INTO `interest_dic` VALUES (178, 'Multiple Antennas', 1);
INSERT INTO `interest_dic` VALUES (179, 'Experimental Data', 1);
INSERT INTO `interest_dic` VALUES (180, 'FORTRAN', 1);
INSERT INTO `interest_dic` VALUES (181, 'Gene Expression', 1);
INSERT INTO `interest_dic` VALUES (182, 'P2P', 1);
INSERT INTO `interest_dic` VALUES (183, 'System Architecture', 1);
INSERT INTO `interest_dic` VALUES (184, 'General Methods', 1);
INSERT INTO `interest_dic` VALUES (185, 'Statistical Method', 1);
INSERT INTO `interest_dic` VALUES (186, 'Adaptive Control', 1);
INSERT INTO `interest_dic` VALUES (187, 'Polymorphism', 1);
INSERT INTO `interest_dic` VALUES (188, 'Polynomial Time Algorithm', 1);
INSERT INTO `interest_dic` VALUES (189, 'Prior Knowledge', 1);
INSERT INTO `interest_dic` VALUES (190, 'Numerical Simulation', 1);
INSERT INTO `interest_dic` VALUES (191, 'Natural Language Processing', 1);
INSERT INTO `interest_dic` VALUES (192, 'Necessary and Sufficient Condition', 1);
INSERT INTO `interest_dic` VALUES (193, 'Time Dependent', 1);
INSERT INTO `interest_dic` VALUES (194, 'Data Flow', 1);
INSERT INTO `interest_dic` VALUES (195, 'Unsupervised Learning', 1);
INSERT INTO `interest_dic` VALUES (196, 'Mobile Device', 1);
INSERT INTO `interest_dic` VALUES (197, 'Supervised Learning', 1);
INSERT INTO `interest_dic` VALUES (198, 'Routing Algorithm', 1);
INSERT INTO `interest_dic` VALUES (199, 'Power Control', 1);
INSERT INTO `interest_dic` VALUES (200, 'Pattern Classification', 1);
INSERT INTO `interest_dic` VALUES (201, 'Software Component', 1);
INSERT INTO `interest_dic` VALUES (202, 'Wireless Ad Hoc Network', 1);
INSERT INTO `interest_dic` VALUES (203, 'Graph Theory', 1);
INSERT INTO `interest_dic` VALUES (204, 'Transfer Function', 1);
INSERT INTO `interest_dic` VALUES (205, 'Network Traffic', 1);
INSERT INTO `interest_dic` VALUES (206, 'Wireless Lan', 1);
INSERT INTO `interest_dic` VALUES (207, 'Scientific Computing', 1);
INSERT INTO `interest_dic` VALUES (208, 'Pattern Matching', 1);
INSERT INTO `interest_dic` VALUES (209, 'Stochastic Process', 1);
INSERT INTO `interest_dic` VALUES (210, 'Digital Image', 1);
INSERT INTO `interest_dic` VALUES (211, 'Profitability', 1);
INSERT INTO `interest_dic` VALUES (212, 'Geometric Model', 1);
INSERT INTO `interest_dic` VALUES (213, 'Theoretical Framework', 1);
INSERT INTO `interest_dic` VALUES (214, 'Distributed Application', 1);
INSERT INTO `interest_dic` VALUES (215, 'Data Compression', 1);
INSERT INTO `interest_dic` VALUES (216, 'Intrusion Detection', 1);
INSERT INTO `interest_dic` VALUES (217, 'Computational Geometry', 1);
INSERT INTO `interest_dic` VALUES (218, 'Heuristic Algorithm', 1);
INSERT INTO `interest_dic` VALUES (219, 'Communication Protocol', 1);
INSERT INTO `interest_dic` VALUES (220, 'Design Methodology', 1);
INSERT INTO `interest_dic` VALUES (221, 'Information Processing', 1);
INSERT INTO `interest_dic` VALUES (222, 'Image Database', 1);
INSERT INTO `interest_dic` VALUES (223, 'Language Model', 1);
INSERT INTO `interest_dic` VALUES (224, 'Radial Basis Function', 1);
INSERT INTO `interest_dic` VALUES (225, 'Numerical Method', 1);
INSERT INTO `interest_dic` VALUES (226, 'Optimization Technique', 1);
INSERT INTO `interest_dic` VALUES (227, 'Information Extraction', 1);
INSERT INTO `interest_dic` VALUES (228, 'Graphic User Interface', 1);
INSERT INTO `interest_dic` VALUES (229, 'Motion Estimation', 1);
INSERT INTO `interest_dic` VALUES (230, 'Linear Matrix Inequality', 1);
INSERT INTO `interest_dic` VALUES (231, 'Dynamic Environment', 1);
INSERT INTO `interest_dic` VALUES (232, 'Mac Protocol', 1);
INSERT INTO `interest_dic` VALUES (233, 'Point To Point', 1);
INSERT INTO `interest_dic` VALUES (234, 'Genetic Program', 1);
INSERT INTO `interest_dic` VALUES (235, 'Integrated Circuit', 1);
INSERT INTO `interest_dic` VALUES (236, 'Cluster Analysis', 1);
INSERT INTO `interest_dic` VALUES (237, 'Multimedia Application', 1);
INSERT INTO `interest_dic` VALUES (238, 'Electronic Commerce', 1);
INSERT INTO `interest_dic` VALUES (239, 'Image Retrieval', 1);
INSERT INTO `interest_dic` VALUES (240, 'Simulation Experiment', 1);
INSERT INTO `interest_dic` VALUES (241, 'Network Performance', 1);
INSERT INTO `interest_dic` VALUES (242, 'Randomized Algorithm', 1);
INSERT INTO `interest_dic` VALUES (243, 'Large Data Sets', 1);
INSERT INTO `interest_dic` VALUES (244, 'Concurrent Programs', 1);
INSERT INTO `interest_dic` VALUES (245, 'User Interaction', 1);
INSERT INTO `interest_dic` VALUES (246, 'Knowledge Acquisition', 1);
INSERT INTO `interest_dic` VALUES (247, 'Theorem Proving', 1);
INSERT INTO `interest_dic` VALUES (248, '3d model', 1);
INSERT INTO `interest_dic` VALUES (249, 'Data Dependence', 1);
INSERT INTO `interest_dic` VALUES (250, 'Stochastic Model', 1);
INSERT INTO `interest_dic` VALUES (251, 'Linear Equations', 1);
INSERT INTO `interest_dic` VALUES (252, 'Medium Access Control', 1);
INSERT INTO `interest_dic` VALUES (253, 'Numerical Solution', 1);
INSERT INTO `interest_dic` VALUES (254, 'Image Compression', 1);
INSERT INTO `interest_dic` VALUES (255, 'Wireless Channels', 1);
INSERT INTO `interest_dic` VALUES (256, 'Knowledge Management', 1);
INSERT INTO `interest_dic` VALUES (257, 'Adaptive Algorithm', 1);
INSERT INTO `interest_dic` VALUES (258, 'Markov Random Field', 1);
INSERT INTO `interest_dic` VALUES (259, 'Hybrid System', 1);
INSERT INTO `interest_dic` VALUES (260, 'Formal Specification', 1);
INSERT INTO `interest_dic` VALUES (261, 'Business Process', 1);
INSERT INTO `interest_dic` VALUES (262, 'Robot Manipulator', 1);
INSERT INTO `interest_dic` VALUES (263, '自动机理论', 1);
INSERT INTO `interest_dic` VALUES (264, '递归论', 1);
INSERT INTO `interest_dic` VALUES (265, '计算复杂性理论', 1);
INSERT INTO `interest_dic` VALUES (266, '密码学', 1);
INSERT INTO `interest_dic` VALUES (267, '量子计算论', 1);
INSERT INTO `interest_dic` VALUES (268, '计算理论', 1);
INSERT INTO `interest_dic` VALUES (269, '算法与数据结构', 1);
INSERT INTO `interest_dic` VALUES (270, '软件工程', 1);
INSERT INTO `interest_dic` VALUES (271, '人工智能', 1);
INSERT INTO `interest_dic` VALUES (272, '计算机网络与通信', 1);
INSERT INTO `interest_dic` VALUES (273, '数据库系统', 1);
INSERT INTO `interest_dic` VALUES (274, '并行计算', 1);
INSERT INTO `interest_dic` VALUES (275, '分布式计算', 1);
INSERT INTO `interest_dic` VALUES (276, '人机交互', 1);
INSERT INTO `interest_dic` VALUES (277, '计算机图形学', 1);
INSERT INTO `interest_dic` VALUES (278, '操作系统', 1);
INSERT INTO `interest_dic` VALUES (279, '数值计算', 1);
INSERT INTO `interest_dic` VALUES (280, '数据结构', 1);
INSERT INTO `interest_dic` VALUES (281, '算法分析', 1);
INSERT INTO `interest_dic` VALUES (282, '计算几何', 1);
INSERT INTO `interest_dic` VALUES (283, '图论', 1);
INSERT INTO `interest_dic` VALUES (284, '编译器', 1);
INSERT INTO `interest_dic` VALUES (285, '程序设计', 1);
INSERT INTO `interest_dic` VALUES (286, '形式化方法', 1);
INSERT INTO `interest_dic` VALUES (287, '形式语义学', 1);
INSERT INTO `interest_dic` VALUES (288, 'Petri网', 1);
INSERT INTO `interest_dic` VALUES (289, '进程演算', 1);
INSERT INTO `interest_dic` VALUES (290, 'PRAM模型', 1);
INSERT INTO `interest_dic` VALUES (291, '数据库模型', 1);
INSERT INTO `interest_dic` VALUES (292, '信息检索', 1);
INSERT INTO `interest_dic` VALUES (293, '数据挖掘', 1);
INSERT INTO `interest_dic` VALUES (294, '社会网络', 1);
INSERT INTO `interest_dic` VALUES (295, '社交网站', 1);
INSERT INTO `interest_dic` VALUES (296, '复杂网络', 1);
INSERT INTO `interest_dic` VALUES (297, '信息抽取', 1);
INSERT INTO `interest_dic` VALUES (298, '自然语言处理', 1);
INSERT INTO `interest_dic` VALUES (299, '机器学习', 1);
INSERT INTO `interest_dic` VALUES (300, '模式识别', 1);
INSERT INTO `interest_dic` VALUES (301, '计算机视觉', 1);
INSERT INTO `interest_dic` VALUES (302, '图像处理', 1);
INSERT INTO `interest_dic` VALUES (303, '认知科学', 1);
INSERT INTO `interest_dic` VALUES (304, '进化计算', 1);
INSERT INTO `interest_dic` VALUES (305, '知识表示', 1);
INSERT INTO `interest_dic` VALUES (306, '机器人科学', 1);
INSERT INTO `interest_dic` VALUES (307, '数字电路', 1);
INSERT INTO `interest_dic` VALUES (308, '传感器网络', 1);
INSERT INTO `interest_dic` VALUES (309, '无线传感', 1);
INSERT INTO `interest_dic` VALUES (310, '微结构', 1);
INSERT INTO `interest_dic` VALUES (311, '多处理机', 1);
INSERT INTO `interest_dic` VALUES (312, '计算机安全', 1);
INSERT INTO `interest_dic` VALUES (313, '网络安全', 1);
INSERT INTO `interest_dic` VALUES (314, '普适计算', 1);
INSERT INTO `interest_dic` VALUES (315, '体系结构', 1);
INSERT INTO `interest_dic` VALUES (316, '编译器设计', 1);
INSERT INTO `interest_dic` VALUES (317, '编程语言', 1);
INSERT INTO `interest_dic` VALUES (318, '云计算', 1);
INSERT INTO `interest_dic` VALUES (319, '生物信息学', 1);
INSERT INTO `interest_dic` VALUES (320, '计算机物理学', 1);
INSERT INTO `interest_dic` VALUES (321, '计算化学', 1);
INSERT INTO `interest_dic` VALUES (322, '电子商务', 1);
INSERT INTO `interest_dic` VALUES (323, '计算机仿真', 1);
INSERT INTO `interest_dic` VALUES (324, '高性能计算机', 1);
INSERT INTO `interest_dic` VALUES (325, '嵌入式计算机', 1);
INSERT INTO `interest_dic` VALUES (326, '微型计算机', 1);
INSERT INTO `interest_dic` VALUES (327, '量子计算机', 1);
INSERT INTO `interest_dic` VALUES (328, '神经网络', 1);
INSERT INTO `interest_dic` VALUES (329, '贝叶斯网络', 1);
INSERT INTO `interest_dic` VALUES (330, '海量数据', 1);
INSERT INTO `interest_dic` VALUES (331, '空间数据', 1);
INSERT INTO `interest_dic` VALUES (332, '统计', 1);
INSERT INTO `interest_dic` VALUES (333, '数据仓库', 1);
INSERT INTO `interest_dic` VALUES (334, 'web数据挖掘', 1);
INSERT INTO `interest_dic` VALUES (335, '高速数据采集', 1);
INSERT INTO `interest_dic` VALUES (336, '多传感器数据融合', 1);
INSERT INTO `interest_dic` VALUES (337, '元搜索', 1);
INSERT INTO `interest_dic` VALUES (338, '语义网', 1);
INSERT INTO `interest_dic` VALUES (339, '下一代互联网', 1);
INSERT INTO `interest_dic` VALUES (340, '移动互联网', 1);
INSERT INTO `interest_dic` VALUES (341, '移动通信', 1);
INSERT INTO `interest_dic` VALUES (342, '人脸识别', 1);
INSERT INTO `interest_dic` VALUES (343, 'Hadoop', 1);
INSERT INTO `interest_dic` VALUES (344, '云存储', 1);
INSERT INTO `interest_dic` VALUES (345, '协同软件', 1);
INSERT INTO `interest_dic` VALUES (346, '科研信息化', 1);
INSERT INTO `interest_dic` VALUES (347, '自动化测试', 1);
INSERT INTO `interest_dic` VALUES (348, '多媒体', 1);
INSERT INTO `interest_dic` VALUES (349, '知识系统', 1);
INSERT INTO `interest_dic` VALUES (350, '机器翻译', 1);
INSERT INTO `interest_dic` VALUES (351, '自动摘要', 1);
INSERT INTO `interest_dic` VALUES (352, '数字水印', 1);
INSERT INTO `interest_dic` VALUES (353, '三维几何', 1);
INSERT INTO `interest_dic` VALUES (354, 'WebES', 1);
INSERT INTO `interest_dic` VALUES (355, '推荐系统', 1);
INSERT INTO `interest_dic` VALUES (356, '文本挖掘', 1);
