 var latexConfig=[
                  ["\\sqrt{x}","√"],
                  ["\\sqrt[n]{x}","∛"],
                  ["x^n","x²"],
                  ["x_n","x₂"],
                  ["x_a^b","x₂²"],
                  ["\\frac{a}{b}","÷"],
                  ["\\lim_{x \\to 0}","limit"],
                  ["\\sum_{a}^{b}","∑"],
                  ["\\int_{a}^{b}","∫"],
                  ["\\oint_{a}^{b}","∮"],
                  ["\\prod_{a}^{b}","∏"],
                  ["\\binom{n}{k}","binom"],
                  ["\\left( \\right)","( )"],
                  ["\\left[ \\right]","[ ]"],
                  ["\\lceil x \\rceil","⌈ x ⌉"],
                  ["\\lfloor x \\rfloor","⌊ x ⌋"],
                  ["\\left\\{ \\right\\}","{ }"],
                  ["\\bigcup_{\\alpha\\in S}","⋃"],
                  ["\\bigcap_{\\alpha\\in S}","⋂"],
                  ["\\partial","∂"],
                  ["\\infty","∞"],
                  ["\\therefore","∴"],
                  ["\\displaystyle","displaystyle"],
                  ["\\textstyle","textstyle"],
                  ["\\scriptstyle","scriptstyle"],
                  ["\\text{}","text"],
                  ["\\textbf{}","bold"],
                  ["\\textit{}","ital"],
                  ["\\textrm{}","roman"],
                  ["{\\color{red} }","R"],
                  ["{\\color{green} }","G"],
                  ["{\\color{blue} }","B"],
                  ["|","|"],
                    ["\\alpha","ɑ"],
                    ["\\beta","β"],
                    ["\\gamma","ɣ"],
                    ["\\delta","δ"],
                    ["\\epsilon","ϵ"],
                    ["\\varepsilon","ε"],
                    ["\\zeta","ζ"],
                    ["\\eta","η"],
                    ["\\theta","θ"],
                    ["\\vartheta","ϑ"],
                    ["\\iota","ι"],
                    ["\\kappa","κ"],
                    ["\\lambda","λ"],
                    ["\\mu","μ"],
                    ["\\nu","ν"],
                    ["\\xi","ξ"],
                    ["\\pi","π"],
                    ["\\varpi","ϖ"],
                    ["\\rho","ρ"],
                    ["\\varrho","ϱ"],
                    ["\\sigma","σ"],
                    ["\\varsigma","ς"],
                    ["\\tau","τ"],
                    ["\\upsilon","υ"],
                    ["\\phi","ϕ"],
                    ["\\varphi","φ"],
                    ["\\chi","χ"],
                    ["\\psi","ψ"],
                    ["\\omega","ω"],
                    ["|","|"]  ,
                    ["\\Gamma","Ɣ"],
                    ["\\Delta","Δ"],
                    ["\\Theta","Θ"],
                    ["\\Lambda","Λ"],
                    ["\\Xi","Ξ"],
                    ["\\Pi","Π"],
                    ["\\Sigma","Σ"],
                    ["\\Upsilon","Υ"],
                    ["\\Psi","Ψ"],
                    ["\\Omega","Ω"]];
